# Generated by Django 4.2.17 on 2025-02-02 13:36

from django.db import migrations
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rule_based_perms", "0001_initial"),
    ]

    def add_rule_config(apps, schema_editor):
        Group = apps.get_model("auth", "Group")
        RuleConfig = apps.get_model("rule_based_perms", "RuleConfig")
        resource_reviewers = Group.objects.get(name="Resource Reviewer")
        rc = RuleConfig.objects.create(
            id=uuid.UUID("baca30f6-96f6-4191-9fa1-f65cb0e3808d"),
            type="filter_tile_has_value",
            node_id=uuid.UUID("8f3f9562-9dc5-11ed-a2fb-0242ac130004"),
            nodegroup_id=uuid.UUID("8f3f9562-9dc5-11ed-a2fb-0242ac130004"),
            value={"value": 75, "op": "eq"},
            name="Allow access to resources with tiles that have the value 75",
        )

        rc.groups.set((resource_reviewers,))

        resource_life_cycle_config = RuleConfig.objects.create(
            id=uuid.UUID("7ac3ccec-3321-4dc8-89f5-99894b5c5d65"),
            type="filter_tile_spatial",
            node_id=uuid.UUID("8d30d2a4-9dc5-11ed-a2fb-0242ac130004"),
            nodegroup_id=uuid.UUID("8d30d2a4-9dc5-11ed-a2fb-0242ac130004"),
            value={
                "op": "intersect",
                "value": '{\n    "type": "Polygon", \n    "coordinates": [\n        [\n            [-122.7210418, 39.4537576], \n            [-122.6880746, 38.7803836], \n            [-121.1935648, 38.7032621], \n            [-121.3034552, 39.5639487], \n            [-122.7248331, 39.4534594], \n            [-122.7210418, 39.4537576]  \n        ]\n    ]\n}',
            },
            name="Filter all tiles that have geographic intersection with specified polygon",
        )

        resource_life_cycle_config.groups.set((resource_reviewers,))

    def remove_rule_config(apps, schema_editor):
        RuleConfig = apps.get_model("rule_based_perms", "RuleConfig")
        RuleConfig.objects.get(
            id=uuid.UUID("7ac3ccec-3321-4dc8-89f5-99894b5c5d65")
        ).delete()

    operations = [
        migrations.RunPython(add_rule_config, remove_rule_config),
    ]
